export const onUnhandledException = (reason, point) =>
  console.error(`Unhandled Exception : Point ${point} | Resons: ${reason}`);
